# -*- coding: utf-8 -*-
"""Copy of Rentel_Bike_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14hCsSh3PlAhCzwTLOnPDUhgme2JE3SEi
"""

class BikeShop:
    def __init__(self,stock):
        self.stock=stock
    def DisplayBike(self):
        print("Tottal Bikes", self.stock)
    def RentForBike(self,Q):


        if Q<=0:
            print("Enter the positve value OR greater then zero")

        elif Q>self.stock:
            print("enter the value (less then stock)")

        else:
            self.stock=self.stock-Q
            print("Tottall price",Q*100)
            print("Tottall Bike",self.stock)


while True:
    obj=BikeShop(100)
    uc=int(input('''
1.Display Stock
2.Rent A Bike
3.Exit                                                  '''))

    if uc==1:
        obj.DisplayBike()
    elif uc==2:
        n=int(input("enter the quntity"))
        obj.RentForBike(n)
    else:
        break

